---

language: node_js
sudo: required
services:
  - docker
node_js: 12
env:
  - DOCKER_IMAGE_NAME=${DOCKER_USER}/about
before_script:
  - npm run lint
  - npm run stylelint
  - npm run test:ci
  - npm run build
  - npm run export
script:
  - docker build -t ${DOCKER_IMAGE_NAME} .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
    docker push ${DOCKER_IMAGE_NAME}
  fi
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: bash script/deploy about "@docker-compose.yml"
    on:
      branch: master
