language: node_js
sudo: required
services:
- docker
node_js: 8
script: |
  npm run build
  DOCKER_IMAGE_NAME=${DOCKER_USER}/about
  docker build -t ${DOCKER_IMAGE_NAME} .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
    docker push ${DOCKER_IMAGE_NAME}
  fi
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.simrobin.fr/deploy/about/ --data-binary @docker-compose.yml"
  on:
    branch: master
